"use client";
/* eslint-disable @next/next/no-html-link-for-pages */

import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import {
  ArrowDownRight, ArrowRight, BarChart3, BrainCircuit, Check,
  ChevronRight, CircleAlert, CircleCheck, Compass, FileSearch, Filter,
  Gauge, Globe2, Layers3, Menu, Network, Play, Search, Send,
  ShieldCheck, Sparkles, Sun, Target, X, Zap,
} from "lucide-react";
import { createContext, useContext, useEffect, useState } from "react";
import { InfrastructureSignalPage, SignalHeroGraphic } from "./InfrastructureSignal";

type IconType = typeof Network;

const industries = ["Infrastructure", "Energy", "Artificial Intelligence", "Governments", "Investment Funds", "Industrial Developers", "Utilities", "Manufacturing"];
const process = [
  ["01", "Understand", "Frame the objective, the decision owner and the cost of being wrong."],
  ["02", "Analyze reality", "Map the operating environment, constraints and dependencies."],
  ["03", "Search evidence", "Gather source-backed signals across documents, data and context."],
  ["04", "Challenge", "Expose assumptions, contradictions and critical unknowns."],
  ["05", "Model paths", "Compare conservative, balanced, growth and transformational scenarios."],
  ["06", "Recommend", "Deliver the strongest decision with confidence and next actions."],
];
const scenarioData = {
  Conservative: { confidence: "78%", value: "$18.4M", risk: "Lower execution risk", note: "Protect downside while preserving optionality." },
  Balanced: { confidence: "84%", value: "$31.8M", risk: "Moderate execution risk", note: "Best evidence-to-upside balance for the current brief." },
  Growth: { confidence: "71%", value: "$46.2M", risk: "Higher execution risk", note: "Capture demand early with staged capital gates." },
  Transformational: { confidence: "58%", value: "$82.6M", risk: "Highest execution risk", note: "Create a new category if the unknowns resolve." },
};
type Scenario = keyof typeof scenarioData;
type Lang = "en" | "es";
const LanguageContext = createContext<{ lang: Lang; setLang: (value: Lang) => void }>({ lang: "en", setLang: () => undefined });
function useLang() { return useContext(LanguageContext); }
function tr(lang: Lang, en: string, es: string) { return lang === "es" ? es : en; }
function track(event: string) { if (typeof window !== "undefined") window.dispatchEvent(new CustomEvent("sagar:analytics", { detail: { event } })); }

function BrandMark() { return <span className="brand-mark" aria-hidden="true"><i /><i /><i /></span>; }

function Header({ theme, setTheme }: { theme: "dark" | "light"; setTheme: (value: "dark" | "light") => void }) {
  const { lang, setLang } = useLang();
  const [open, setOpen] = useState(false);
  const links = [[tr(lang, "Infrastructure Signal", "Infrastructure Signal"), "/infrastructure-signal"], [tr(lang, "How It Works", "Cómo funciona"), "/how-it-works"], [tr(lang, "Decision Room", "Sala de Decisiones"), "/decision-room"], [tr(lang, "Use Cases", "Casos de uso"), "/use-cases"], [tr(lang, "Company", "Compañía"), "/about"]];
  return <header className="site-header">
    <a className="brand" href="/" aria-label="Sagar Labs home"><BrandMark /><span>SAGAR <b>LABS</b></span></a><span className="beta-badge">BETA</span>
    <nav className="desktop-nav" aria-label="Primary navigation">{links.map(([label, href]) => <a href={href} key={label}>{label}</a>)}</nav>
    <div className="header-actions"><div className="language-toggle" aria-label="Language selector"><button className={lang === "en" ? "active" : ""} onClick={() => { setLang("en"); track("language_change"); }}>EN</button><button className={lang === "es" ? "active" : ""} onClick={() => { setLang("es"); track("language_change"); }}>ES</button></div><button className="theme-toggle" onClick={() => setTheme(theme === "dark" ? "light" : "dark")} aria-label={`Switch to ${theme === "dark" ? "light" : "dark"} mode`}>{theme === "dark" ? <Sun size={15} /> : <Sparkles size={15} />}</button><a className="header-cta" href="/contact" onClick={() => track("hero_start_decision")}>{tr(lang, "Start a Decision", "Iniciar una decisión")} <ArrowRight size={14} /></a></div>
    <button className="menu-button" onClick={() => setOpen(!open)} aria-expanded={open} aria-label="Open navigation">{open ? <X /> : <Menu />}</button>
    <AnimatePresence>{open && <motion.nav className="mobile-nav" initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}><div className="mobile-language"><button className={lang === "en" ? "active" : ""} onClick={() => setLang("en")}>English</button><button className={lang === "es" ? "active" : ""} onClick={() => setLang("es")}>Español</button></div><div>{links.map(([label, href]) => <a href={href} key={label} onClick={() => setOpen(false)}>{label}<ChevronRight size={16} /></a>)}</div><a className="button primary" href="/contact">{tr(lang, "Start a Decision", "Iniciar una decisión")} <ArrowRight size={15} /></a></motion.nav>}</AnimatePresence>
  </header>;
}

function Footer() { const { lang } = useLang(); return <footer><div className="footer-brand"><a className="brand" href="/"><BrandMark /><span>SAGAR <b>LABS</b></span></a><p>{tr(lang, "Decision Intelligence for Humanity.", "Inteligencia de decisiones para la humanidad.")}</p></div><div><span>{tr(lang, "Experience", "Experiencia")}</span><a href="/how-it-works">{tr(lang, "How It Works", "Cómo funciona")}</a><a href="/decision-room">{tr(lang, "Decision Room", "Sala de Decisiones")}</a><a href="/evidence-explorer">{tr(lang, "Evidence Explorer", "Explorador de evidencia")}</a></div><div><span>{tr(lang, "Company", "Compañía")}</span><a href="/use-cases">{tr(lang, "Use Cases", "Casos de uso")}</a><a href="/pricing">{tr(lang, "Decision Sprint", "Decision Sprint")}</a><a href="/contact">{tr(lang, "Contact", "Contacto")}</a></div><small>© 2026 Sagar Labs · {tr(lang, "Private beta · Evidence. Reasoning. Transformation.", "Beta privada · Evidencia. Razonamiento. Transformación.")}</small></footer>; }

function Reveal({ children, className = "" }: { children: React.ReactNode; className?: string }) { const reduce = useReducedMotion(); return <motion.div className={className} initial={reduce ? false : { opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-10%" }} transition={{ duration: .7, ease: [0.22, 1, 0.36, 1] }}>{children}</motion.div>; }

function SectionIntro({ index, eyebrow, title, text, light = false }: { index: string; eyebrow: string; title: React.ReactNode; text?: string; light?: boolean }) { return <div className={`section-intro ${light ? "light" : ""}`}><span className="kicker"><i>{index}</i>{eyebrow}</span><h2>{title}</h2>{text && <p>{text}</p>}</div>; }

function DecisionRoomPreview() {
  const [scenario, setScenario] = useState<Scenario>("Balanced");
  const data = scenarioData[scenario];
  return <div className="room-shell">
    <div className="room-sidebar"><div className="room-status"><span className="live-dot" /> Decision Sprint <b>In review</b></div><div className="room-list"><span>Decision brief</span><span className="active">Executive Decision</span><span>Evidence coverage</span><span>Scenarios</span><span>Open questions</span></div><div className="room-footer"><span>Last synthesized</span><b>Today, 09:42 UTC</b></div></div>
    <div className="room-main"><div className="room-top"><span className="mono-label">ILLUSTRATIVE DEMO / DECISION ROOM 001</span><span className="room-sync"><span className="live-dot" /> Demo data</span></div><div className="room-heading"><div><span className="mono-label">EXECUTIVE DECISION</span><h3>Proceed with a staged AI infrastructure expansion.</h3><p>Evidence supports moving forward with a gated first phase while resolving two material power and water unknowns.</p></div><div className="confidence"><Gauge size={17} /><small>Confidence</small><strong>{data.confidence}</strong><span>Illustrative</span></div></div><div className="room-metrics"><div><span>Evidence coverage</span><b>84%</b><i><em style={{ width: "84%" }} /></i></div><div><span>Critical unknowns</span><b>02</b><small>Need resolution</small></div><div><span>Top risks</span><b>03</b><small>Actively monitored</small></div><div><span>Opportunities</span><b>07</b><small>Connected signals</small></div></div><div className="room-lower"><div className="decision-why"><span className="mono-label">WHY THIS DECISION</span><div><CircleCheck size={16} /><p>Secure the site option before competing demand changes the economics.</p></div><div><CircleCheck size={16} /><p>Preserve capital flexibility with an explicit phase gate.</p></div><div className="warning"><CircleAlert size={16} /><p>Confirm substation delivery date and water allocation before final investment committee approval.</p></div></div><div className="room-scenarios"><div className="scenario-head"><span className="mono-label">SCENARIO SIGNAL / ILLUSTRATIVE</span><a href="/scenario-explorer">Explore <ArrowRight size={13} /></a></div><div className="scenario-tabs">{(Object.keys(scenarioData) as Scenario[]).map(item => <button className={scenario === item ? "selected" : ""} onClick={() => setScenario(item)} key={item}>{item}</button>)}</div><AnimatePresence mode="wait"><motion.div key={scenario} className="scenario-readout" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }}><div><span>Illustrative value</span><b>{data.value}</b></div><div><span>Profile</span><b>{data.risk}</b></div><p>{data.note}</p></motion.div></AnimatePresence></div></div></div>
  </div>;
}

function Home() { const { lang } = useLang(); return <main>
  <section className="hero-experience"><div className="hero-glow" /><div className="hero-gridline" /><div className="hero-copy"><span className="kicker"><i>00</i>{tr(lang, "Sagar Infrastructure Signal", "Sagar Infrastructure Signal")}</span><h1>{tr(lang, "Public signals are not the same as", "Las señales públicas no son lo mismo que")} <em>{tr(lang, "readiness.", "la preparación.")}</em></h1><p>{tr(lang, "Every great decision begins with a clear evidence boundary. We turn public records into a decision boundary: what the evidence supports, what it cannot support and what should happen next.", "Toda gran decisión comienza con un límite claro de evidencia. Convertimos registros públicos en un límite de decisión: qué respalda la evidencia, qué no puede respaldar y qué debe suceder después.")}</p><div className="hero-actions"><a className="button primary" href="/infrastructure-signal" onClick={() => track("hero_view_signal")}>{tr(lang, "Read the Signal", "Leer la señal")} <ArrowRight size={16} /></a><a className="button ghost" href="/contact" onClick={() => track("hero_start_decision")}>{tr(lang, "Bring a Decision", "Tráenos una decisión")} <ArrowRight size={15} /></a><a className="subtle-cta" href="#decision-room" onClick={() => track("hero_view_demo")}><span className="play-icon"><Play size={11} fill="currentColor" /></span> {tr(lang, "View Demo", "Ver demo")}</a></div><div className="hero-proof"><ShieldCheck size={15} /><span>{tr(lang, "CYCLE_013 / public evidence", "CYCLE_013 / evidencia pública")}</span><i /> <span>{tr(lang, "9 sources indexed", "9 fuentes indexadas")}</span><i /> <span>{tr(lang, "Advance eligible: NO", "Elegible para avanzar: NO")}</span></div></div><div className="hero-visual"><SignalHeroGraphic lang={lang} /></div><div className="scroll-marker"><span>{tr(lang, "Scroll to explore", "Desplázate para explorar")}</span><ArrowDownRight size={14} /></div></section>
  <section className="trust-strip"><span>Built for decisions across</span>{industries.map(item => <span key={item}>{item}</span>)}</section>
  <section className="problem-section"><Reveal><SectionIntro index="01" eyebrow={tr(lang, "The problem", "El problema")} title={<>{tr(lang, "Complex decisions fail when critical realities remain", "Las decisiones complejas fallan cuando las realidades críticas permanecen")} <em>{tr(lang, "disconnected.", "desconectadas.")}</em></>} text={tr(lang, "Power, water, permitting, community, environment, capital and execution rarely arrive in one coherent view. Sagar connects them into one decision system.", "La energía, el agua, los permisos, la comunidad, el entorno, el capital y la ejecución rara vez llegan en una visión coherente. Sagar los conecta en un solo sistema de decisión.")} /></Reveal><div className="problem-cloud">{["Power", "Water", "Permitting", "Community", "Environment", "Capital", "Execution", "Security", "Geopolitics", "Supply Chain"].map((item, i) => <div className={`problem-chip pc-${i}`} key={item}><span>{item}</span><i /></div>)}</div></section>
  <section className="thesis-section"><Reveal><SectionIntro index="01" eyebrow="The premise" title={<>The product is not AI.<br /><em>The product is confidence.</em></>} text="The world is full of information. The hard part is knowing what matters, what is missing and what to do next. Sagar Labs turns fragmented reality into a clear path forward." /></Reveal><div className="thesis-rail"><div><span>01</span><b>Evidence</b><p>Know what is true, what is inferred and what remains unknown.</p></div><div><span>02</span><b>Reasoning</b><p>Challenge assumptions and compare the consequences of each path.</p></div><div><span>03</span><b>Transformation</b><p>Move from insight to a decision your organization can act on.</p></div></div></section>
  <section className="room-section" id="decision-room"><Reveal><SectionIntro index="02" eyebrow="Decision Room" title={<>The room where<br /><em>clarity compounds.</em></>} text="A calm, governed workspace for the decisions that carry the most consequence." /></Reveal><Reveal className="room-preview"><DecisionRoomPreview /></Reveal><div className="center-link"><a href="/decision-room">Enter the Decision Room <ArrowRight size={15} /></a></div></section>
  <section className="process-section"><Reveal><SectionIntro index="03" eyebrow={tr(lang, "How Sagar works", "Cómo funciona Sagar")} title={<>{tr(lang, "Six moves from", "Seis movimientos de")}<br /><em>{tr(lang, "uncertainty to action.", "incertidumbre a acción.")}</em></>} text={tr(lang, "The system behaves like an elite council of experts: curious, rigorous, transparent and accountable.", "El sistema se comporta como un consejo de expertos: curioso, riguroso, transparente y responsable.")} /></Reveal><div className="process-grid">{process.map(([number, title, text], index) => <Reveal className="process-card" key={number}><span>{number}</span>{index < process.length - 1 && <ArrowRight className="process-arrow" size={15} />}<div className="process-icon">{[Target, Globe2, FileSearch, CircleAlert, BarChart3, Sparkles].map((Icon, i) => i === index ? <Icon key={title} size={18} /> : null)}</div><h3>{lang === "es" ? ["Entender", "Analizar la realidad", "Buscar evidencia", "Desafiar", "Comparar caminos", "Recomendar"][index] : title}</h3><p>{lang === "es" ? ["Enmarcar el objetivo, el responsable y el costo de equivocarse.", "Mapear el entorno operativo, las restricciones y dependencias.", "Reunir señales respaldadas por fuentes y contexto.", "Exponer supuestos, contradicciones e incógnitas críticas.", "Comparar caminos estratégicos y sus consecuencias.", "Entregar la decisión mejor respaldada y sus próximos pasos."][index] : text}</p></Reveal>)}</div></section>
  <section className="deliverables-section"><Reveal><SectionIntro index="04" eyebrow={tr(lang, "What you receive", "Lo que recibes")} title={<>{tr(lang, "A decision system, not", "Un sistema de decisión, no un")} <em>{tr(lang, "a static report.", "informe estático.")}</em></>} text={tr(lang, "Every engagement leaves an executive layer your team can inspect, challenge and act on.", "Cada encargo deja una capa ejecutiva que tu equipo puede inspeccionar, cuestionar y convertir en acción.")} /></Reveal><div className="deliverable-grid">{["Executive Decision", "Risk Map", "Opportunity Map", "Evidence Explorer", "Scenario Analysis", "Transformation Roadmap", "Critical Unknowns", "Action Plan", "Decision Confidence"].map((item, i) => <div className="deliverable-card" key={item}><span>0{i + 1}</span><b>{lang === "es" ? ["Decisión ejecutiva", "Mapa de riesgos", "Mapa de oportunidades", "Explorador de evidencia", "Análisis de escenarios", "Hoja de transformación", "Incógnitas críticas", "Plan de acción", "Confianza de decisión"][i] : item}</b><ArrowRight size={14} /></div>)}</div></section>
  <section className="graph-section"><Reveal><SectionIntro index="05" eyebrow={tr(lang, "Decision Intelligence", "Inteligencia de decisiones")} title={<>{tr(lang, "See the decision", "Mira la decisión")}<br /><em>{tr(lang, "before you make it.", "antes de tomarla.")}</em></>} text={tr(lang, "Evidence, unknowns, risks, opportunities and scenarios are connected in one living model of reality.", "La evidencia, las incógnitas, los riesgos, las oportunidades y los escenarios se conectan en un modelo vivo de la realidad.")} /><a className="text-link" href="/decision-intelligence">{tr(lang, "Explore the decision layer", "Explorar la capa de decisión")} <ArrowRight size={15} /></a></Reveal><Reveal className="graph-map"><div className="graph-center"><BrandMark /><b>DECISION</b><span>Confidence layer</span></div>{["Evidence", "Unknowns", "Risks", "Scenarios", "Opportunities", "Actions"].map((label, i) => <div className={`graph-bubble gb-${i}`} key={label}><span>{lang === "es" ? ["Evidencia", "Incógnitas", "Riesgos", "Escenarios", "Oportunidades", "Acciones"][i] : label}</span><i /></div>)}<div className="graph-line gl-1" /><div className="graph-line gl-2" /><div className="graph-line gl-3" /><div className="graph-line gl-4" /><div className="graph-line gl-5" /><div className="graph-ring gr-1" /><div className="graph-ring gr-2" /></Reveal></section>
  <section className="demo-section"><Reveal><SectionIntro index="06" eyebrow={tr(lang, "Decision Room demo", "Demo de la Sala de Decisiones")} title={<>{tr(lang, "See the work", "Mira el trabajo")}<br /><em>{tr(lang, "before the meeting.", "antes de la reunión.")}</em></>} text={tr(lang, "Illustrative demo data. Not a client result.", "Datos ilustrativos de demo. No son resultados de un cliente.")} /></Reveal><div className="demo-grid"><div className="demo-context"><span className="mono-label">ILLUSTRATIVE DEMO / NORTHERN NEVADA AI CAMPUS</span><h3>Validate the site before committing capital.</h3><div className="demo-status"><span>Decision status</span><b>MODERATE CONFIDENCE</b></div><div className="demo-context-list"><div><span>Critical unknowns</span><b>05</b></div><div><span>Highest risk</span><b>Power availability</b></div><div><span>Best opportunity</span><b>Regional AI cluster</b></div><div><span>Next best evidence</span><b>Utility service letter</b></div></div></div><div className="demo-evidence"><span className="mono-label">RECOMMENDATION TRACE</span><div className="demo-trace"><div><CircleCheck size={15} /><span>Known fact</span><b>Site has secured water rights</b></div><div><CircleAlert size={15} /><span>Critical unknown</span><b>Substation delivery schedule</b></div><div><Sparkles size={15} /><span>Opportunity</span><b>Stage power for a regional AI hub</b></div></div><a href="/decision-room" className="text-link" onClick={() => track("demo_complete")}>{tr(lang, "Open guided demo", "Abrir demo guiado")} <ArrowRight size={15} /></a></div></div></section>
  <section className="paths-section"><Reveal><SectionIntro index="07" eyebrow={tr(lang, "Strategic paths", "Caminos estratégicos")} title={<>{tr(lang, "Four ways forward.", "Cuatro caminos posibles.")}<br /><em>{tr(lang, "One decision to make.", "Una decisión que tomar.")}</em></>} /></Reveal><div className="path-grid">{[["Fastest", "Medium", "12–18 mo", "High", "Power delivery", "Win on speed"], ["Lowest Risk", "High", "24–36 mo", "Medium", "Permitting", "Win on certainty"], ["Highest Potential", "High", "18–30 mo", "High", "Demand growth", "Win on scale"], ["Transformational", "Very high", "36+ mo", "Very high", "Multiple dependencies", "Win on new category"]].map(([title, capex, time, complexity, dependency, why], i) => <div className={`path-card path-${i}`} key={title}><span className="mono-label">0{i + 1} / APPROACH</span><h3>{title}</h3><div><span>CAPEX</span><b>{capex}</b></div><div><span>TIME</span><b>{time}</b></div><div><span>COMPLEXITY</span><b>{complexity}</b></div><div><span>MAIN DEPENDENCY</span><b>{dependency}</b></div><small>{why}</small></div>)}</div></section>
  <section className="discovery-section"><Reveal><SectionIntro index="08" eyebrow={tr(lang, "Opportunity Discovery", "Descubrimiento de oportunidades")} title={<>{tr(lang, "What if the best opportunity", "¿Y si la mejor oportunidad")}<br /><em>{tr(lang, "isn't the one you asked us to evaluate?", "no es la que nos pediste evaluar?")}</em></>} text={tr(lang, "We test the original idea against adjacent paths that may reduce risk, improve resilience or create more strategic value.", "Probamos la idea original contra caminos alternativos que pueden reducir el riesgo, mejorar la resiliencia o crear más valor estratégico.")} /></Reveal><div className="discovery-flow"><div className="discovery-node original"><span>Original idea</span><b>Hyperscale Data Center</b></div><ArrowRight size={18} /><div className="discovery-options"><div><span>Alternative path</span><b>Edge AI</b></div><div><span>Alternative path</span><b>Disaster Recovery</b></div><div><span>Alternative path</span><b>Regional AI Hub</b></div></div></div></section>
  <section className="method-section"><Reveal><SectionIntro index="09" eyebrow={tr(lang, "Evidence first", "Evidencia primero")} title={<>{tr(lang, "Every important recommendation", "Toda recomendación importante")}<br /><em>{tr(lang, "should be traceable.", "debe ser trazable.")}</em></>} text={tr(lang, "Sagar distinguishes facts, evidence, assumptions, hypotheses and unknowns. Unknowns do not silently become conclusions.", "Sagar distingue hechos, evidencia, supuestos, hipótesis e incógnitas. Las incógnitas no se convierten silenciosamente en conclusiones.")} /></Reveal><div className="method-grid">{[["FACT", "What is directly observed or documented."], ["EVIDENCE", "A source that supports or weakens a claim."], ["ASSUMPTION", "A condition used to explore a path."], ["HYPOTHESIS", "A strategic interpretation requiring validation."], ["UNKNOWN", "A gap that can change the decision."], ["EXPERT REVIEW", "Human judgment when stakes or ambiguity require it."]].map(([label, text]) => <div key={label}><span>{label}</span><p>{text}</p></div>)}</div></section>
  <section className="comparison-section"><Reveal><SectionIntro index="10" eyebrow={tr(lang, "A living decision record", "Un registro vivo de decisión")} title={<>{tr(lang, "From periodic analysis", "Del análisis periódico")}<br /><em>{tr(lang, "to continuous clarity.", "a la claridad continua.")}</em></>} /></Reveal><div className="compare-table"><div><span>Traditional project analysis</span><b>Periodic</b><b>Manual</b><b>Fragmented</b><b>Static report</b></div><div className="compare-highlight"><span>Sagar</span><b>Continuous</b><b>Evidence-linked</b><b>Scenario-based</b><b>Auditable</b><b>Living decision record</b></div></div></section>
  <section className="use-case-strip"><Reveal><SectionIntro index="11" eyebrow={tr(lang, "Use cases", "Casos de uso")} title={tr(lang, "Decisions across the systems that matter.", "Decisiones en los sistemas que importan.")} /></Reveal><div className="use-case-list">{["Infrastructure Development", "Data Centers & AI Infrastructure", "Energy", "Industrial Projects", "Site Selection", "Investment Pre-Diligence", "Government / Economic Development", "Manufacturing"].map(item => <a href="/use-cases" key={item}><span>{item}</span><ArrowRight size={14} /></a>)}</div></section>
  <section className="start-section"><Reveal><SectionIntro index="12" eyebrow={tr(lang, "How a client starts", "Cómo empieza un cliente")} title={<>{tr(lang, "Five steps to a", "Cinco pasos hacia una")}<br /><em>{tr(lang, "better decision.", "mejor decisión.")}</em></>} /></Reveal><div className="start-steps">{[tr(lang, "Tell us the decision.", "Cuéntanos la decisión."), tr(lang, "Share available project information.", "Comparte la información disponible."), tr(lang, "We identify evidence and unknowns.", "Identificamos evidencia e incógnitas."), tr(lang, "We evaluate scenarios.", "Evaluamos escenarios."), tr(lang, "You receive a decision roadmap.", "Recibes una hoja de ruta de decisión.")].map((item, i) => <div key={item}><span>0{i + 1}</span><b>{item}</b>{i < 4 && <ArrowRight size={14} />}</div>)}</div></section>
  <section className="offer-section"><Reveal><div className="offer-card"><span className="kicker"><i>13</i>{tr(lang, "Focused engagement", "Encargo enfocado")}</span><h2>Power-to-Compute<br /><em>Decision Sprint</em></h2><p>{tr(lang, "A focused engagement for teams deciding where, when and how to commit to AI infrastructure.", "Un encargo enfocado para equipos que deciden dónde, cuándo y cómo comprometerse con infraestructura de IA.")}</p><div className="offer-deliverables">{[tr(lang, "Executive decision brief", "Brief de decisión ejecutiva"), tr(lang, "Evidence map", "Mapa de evidencia"), tr(lang, "Critical unknowns", "Incógnitas críticas"), tr(lang, "Risk assessment", "Evaluación de riesgos"), tr(lang, "Strategic alternatives", "Alternativas estratégicas"), tr(lang, "Next-step acquisition plan", "Plan de adquisición de próximos pasos")].map(item => <span key={item}><Check size={14} />{item}</span>)}</div><a className="button primary" href="/contact" onClick={() => track("decision_sprint_click")}>{tr(lang, "Request Scope & Pricing", "Solicitar alcance y precio")} <ArrowRight size={15} /></a><small>{tr(lang, "Scope and pricing are confirmed after the decision brief. No public price is hard-coded.", "El alcance y el precio se confirman después del brief de decisión. No se publica un precio fijo.")}</small></div></Reveal></section>
  <section className="scenario-section"><Reveal><SectionIntro index="05" eyebrow="Scenario Explorer" title={<>The strongest decision<br /><em>is rarely the loudest one.</em></>} text="Make the trade-offs visible. Compare paths without losing the evidence beneath them." /></Reveal><div className="scenario-cards">{(Object.keys(scenarioData) as Scenario[]).map((name, i) => <a className={`scenario-card sc-${i}`} href="/scenario-explorer" key={name}><span className="mono-label">0{i + 1} / PATH</span><h3>{name}</h3><p>{scenarioData[name].note}</p><div><b>{scenarioData[name].confidence}</b><span>confidence</span><ArrowRight size={15} /></div></a>)}</div></section>
  <section className="evidence-section"><Reveal className="evidence-copy"><SectionIntro index="06" eyebrow="Evidence Explorer" title={<>A decision is only as strong<br /><em>as its evidence trail.</em></>} text="Trace every recommendation to the documents, sources, contradictions and open questions that shaped it." /><a className="text-link" href="/evidence-explorer">Open evidence explorer <ArrowRight size={15} /></a></Reveal><Reveal className="evidence-window"><div className="evidence-toolbar"><span className="mono-label">EVIDENCE TIMELINE</span><span><Filter size={13} /> 148 sources</span></div><div className="evidence-timeline">{[["09:42", "Decision confidence updated", "Power purchase agreement · Verified", "verified"], ["08:17", "Contradiction detected", "Water allocation memo · Needs review", "warning"], ["YESTERDAY", "New source connected", "Regional grid study · Public source", "new"], ["JUL 18", "Assumption challenged", "Demand forecast · Scenario input", "warning"]].map(([time, title, detail, kind]) => <div className="evidence-row" key={time + title}><span>{time}</span><i className={`evidence-dot ${kind}`} /><div><b>{title}</b><p>{detail}</p></div><ChevronRight size={14} /></div>)}</div><div className="evidence-footer"><span><CircleCheck size={14} /> 92% source traceability</span><a href="/evidence-explorer">View all <ArrowRight size={13} /></a></div></Reveal></section>
  <section className="summary-section"><Reveal><div className="summary-card"><div className="summary-header"><span className="mono-label">CEO SUMMARY / ONE PAGE</span><span className="summary-conf"><Gauge size={14} /> 84% confidence</span></div><div className="summary-body"><span className="kicker"><i>07</i>Recommendation</span><h2>Proceed with a staged expansion.</h2><div className="summary-grid"><div><span>Why</span><p>Timing, site readiness and market pull create an asymmetric opportunity.</p></div><div><span>What could change this</span><p>Substation delivery slips beyond Q2 or water allocation remains unresolved.</p></div><div><span>Immediate actions</span><p>Secure site option · commission grid study · convene investment committee.</p></div></div></div><a className="summary-link" href="/ceo-summary">Open CEO Summary <ArrowRight size={15} /></a></div></Reveal></section>
  <section className="final-cta"><Reveal><span className="kicker"><i>08</i>Next decision</span><h2>Ready to make your next<br /><em>strategic decision?</em></h2><p>Start your first Decision Sprint with the team that turns uncertainty into an advantage.</p><a className="button primary" href="/contact">Start a Decision <ArrowRight size={16} /></a></Reveal></section>
 </main>; }

function DecisionRoomPage() { return <main className="interior-page"><section className="interior-hero"><span className="kicker"><i>01</i>Product experience / Decision Room</span><h1>Where important decisions<br /><em>become clear.</em></h1><p>A governed workspace for executive teams to frame a decision, inspect the evidence, compare scenarios and move with confidence.</p><a className="button primary" href="/contact">Start a Decision <ArrowRight size={16} /></a></section><section className="interior-room"><DecisionRoomPreview /></section><section className="interior-split"><SectionIntro index="02" eyebrow="Built around the decision" title={<>Everything that matters.<br /><em>Nothing that distracts.</em></>} text="The Decision Room keeps the executive layer focused while preserving the depth needed for rigorous review." /><div className="feature-list">{[[BrainCircuit, "Executive Decision", "One recommendation, with the reasoning and trade-offs visible."], [ShieldCheck, "Confidence layer", "Evidence coverage and unknowns are always in the room."], [Layers3, "Decision history", "Every change is traceable. Every assumption can be revisited."]].map(([Icon, title, text]) => { const FeatureIcon = Icon as IconType; return <div className="feature-item" key={title as string}><FeatureIcon size={18} /><div><h3>{title as string}</h3><p>{text as string}</p></div></div>; })}</div></section></main>; }

function ScenarioExplorer() { const [active, setActive] = useState<Scenario>("Balanced"); const data = scenarioData[active]; return <main className="interior-page"><section className="interior-hero compact"><span className="kicker"><i>01</i>Scenario Explorer</span><h1>Make the trade-offs<br /><em>visible.</em></h1><p>Explore the paths available to you, the evidence behind each one and what would need to be true to make it work.</p></section><section className="explorer-shell"><div className="explorer-tabs">{(Object.keys(scenarioData) as Scenario[]).map(name => <button className={name === active ? "active" : ""} onClick={() => setActive(name)} key={name}>{name}<ChevronRight size={14} /></button>)}</div><AnimatePresence mode="wait"><motion.div className="explorer-main" key={active} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}><div className="explorer-heading"><span className="mono-label">SCENARIO / {active.toUpperCase()}</span><h2>{data.note}</h2><p>Designed around the current evidence set. Adjust the assumptions to see how the recommendation changes.</p></div><div className="explorer-stats"><div><span>Confidence</span><b>{data.confidence}</b><i><em style={{ width: data.confidence }} /></i></div><div><span>Expected value</span><b>{data.value}</b><small>vs. current baseline</small></div><div><span>Risk profile</span><b>{data.risk}</b><small>3 monitored signals</small></div></div><div className="explorer-chart"><div className="chart-labels"><span>Upside</span><span>Downside</span></div><div className="chart-grid"><div className="chart-line" /><i className="chart-point cp-1" /><i className="chart-point cp-2" /><i className="chart-point cp-3" /><i className="chart-point cp-4" /><span className="chart-callout">Best evidence-to-upside balance</span></div><div className="chart-axis"><span>Now</span><span>Phase 1</span><span>Phase 2</span><span>Scale</span></div></div></motion.div></AnimatePresence></section><section className="interior-split alt"><SectionIntro index="02" eyebrow="Decision discipline" title={<>A scenario is a promise<br /><em>with conditions.</em></>} text="We make those conditions explicit so leaders can act before the future arrives." /><div className="condition-list">{["What must be true", "What we know", "What could change", "What to do next"].map((item, i) => <div key={item}><span>0{i + 1}</span><b>{item}</b><ArrowRight size={15} /></div>)}</div></section></main>; }

function EvidenceExplorer() { const [filter, setFilter] = useState("All evidence"); const rows = [["Power purchase agreement", "Official document", "Verified", "verified"], ["Water allocation memo", "Internal source", "Needs review", "warning"], ["Regional grid study", "Public source", "Connected", "new"], ["Demand forecast", "Scenario input", "Challenged", "warning"], ["Site control agreement", "Legal document", "Verified", "verified"]]; return <main className="interior-page"><section className="interior-hero compact"><span className="kicker"><i>01</i>Evidence Explorer</span><h1>Follow the trail<br /><em>to confidence.</em></h1><p>Documents, sources, contradictions and unknowns—organized around the decision they influence.</p></section><section className="evidence-explorer"><div className="explorer-header"><div><span className="mono-label">EVIDENCE SET / AI INFRASTRUCTURE</span><h2>148 sources connected</h2></div><div className="search-box"><Search size={15} /><input aria-label="Search evidence" placeholder="Search sources, documents, signals" /></div></div><div className="filter-row">{["All evidence", "Verified", "Needs review", "Unknowns"].map(item => <button key={item} onClick={() => setFilter(item)} className={filter === item ? "active" : ""}>{item}</button>)}</div><div className="source-table"><div className="source-table-head"><span>Source</span><span>Type</span><span>Status</span><span>Updated</span></div>{rows.filter(row => filter === "All evidence" || (filter === "Verified" && row[3] === "verified") || (filter === "Needs review" && row[3] === "warning") || (filter === "Unknowns" && row[2] === "Unknown")).map(row => <div className="source-row" key={row[0]}><div><span className={`evidence-dot ${row[3]}`} /><b>{row[0]}</b></div><span>{row[1]}</span><span className={row[3] === "verified" ? "status-good" : "status-warn"}>{row[2]}</span><span>Today, 09:42</span><ChevronRight size={14} /></div>)}</div><div className="evidence-bottom"><div><CircleCheck size={16} /><span>Source traceability <b>92%</b></span></div><div><CircleAlert size={16} /><span>Critical unknowns <b>02</b></span></div><div><Network size={16} /><span>Graph connections <b>2,481</b></span></div></div></section></main>; }

function CEOPage() { return <main className="interior-page"><section className="interior-hero compact"><span className="kicker"><i>01</i>CEO Summary</span><h1>One page for<br /><em>the decision.</em></h1><p>The executive layer: recommendation, why, risks, opportunities, immediate actions and what could change the call.</p><a className="button primary" href="/contact">Request a Decision Sprint <ArrowRight size={16} /></a></section><section className="ceo-paper"><div className="paper-top"><span className="mono-label">EXECUTIVE DECISION / AI INFRASTRUCTURE EXPANSION</span><span className="summary-conf"><Gauge size={14} /> Confidence 84%</span></div><div className="paper-title"><span>Recommendation</span><h2>Proceed with a staged expansion.</h2><p>Secure the site option now. Advance only when power delivery and water allocation clear the phase gate.</p></div><div className="paper-grid">{[[CircleCheck, "Why", "Market timing, site readiness and demand create an asymmetric opportunity."], [CircleAlert, "Top risks", "Substation delivery, water allocation and execution sequencing."], [Zap, "Opportunities", "Secure an adjacent parcel and negotiate a flexible power tranche."], [ArrowRight, "Immediate actions", "Commission grid study, secure option, convene investment committee."], [Search, "Critical unknowns", "Final water allocation. Verified delivery schedule."], [Compass, "What could change this", "A material schedule slip or unresolved water constraint."]].map(([Icon, title, text]) => { const ItemIcon = Icon as IconType; return <div className="paper-item" key={title as string}><ItemIcon size={16} /><span>{title as string}</span><p>{text as string}</p></div>; })}</div><div className="paper-footer"><span>Prepared from 148 connected sources</span><span>Last synthesized today, 09:42 UTC</span></div></section></main>; }

function About() { return <main className="interior-page"><section className="interior-hero"><span className="kicker"><i>01</i>About Sagar Labs</span><h1>Decision Intelligence<br /><em>for Humanity.</em></h1><p>We help organizations make the best strategic decisions possible—by reducing uncertainty before it becomes cost, delay or regret.</p></section><section className="about-manifesto"><SectionIntro index="02" eyebrow="Our conviction" title={<>The most valuable thing<br /><em>we can give a leader is clarity.</em></>} text="Sagar Labs is building the intelligence layer for a world where infrastructure, energy, technology and institutions are increasingly interconnected." /><div className="about-values">{[[ShieldCheck, "Evidence before confidence"], [BrainCircuit, "Reasoning before reaction"], [Network, "Transformation before theater"], [Target, "Human judgment at the center"]].map(([Icon, label]) => { const AboutIcon = Icon as IconType; return <div key={label as string}><AboutIcon size={18} /><b>{label as string}</b></div>; })}</div></section></main>; }

function Pricing() { return <main className="interior-page"><section className="interior-hero compact"><span className="kicker"><i>01</i>Enterprise access</span><h1>Price the decision<br /><em>you cannot afford to get wrong.</em></h1><p>Every engagement starts with a focused Decision Sprint. Enterprise access expands the evidence layer, workflows and governance around your most consequential decisions.</p></section><section className="pricing-grid">{[["Decision Sprint", "A focused decision, made legible.", "Starting with your highest-consequence question.", ["Decision framing", "Evidence map", "Executive recommendation", "CEO Summary"]], ["Enterprise Intelligence", "A living intelligence layer.", "For teams making decisions across a portfolio.", ["Unlimited Decision Rooms", "Scenario and evidence explorers", "Governed agent workflows", "Executive operating cadence"]], ["Strategic Partnership", "Decision infrastructure, embedded.", "For institutions building a compounding advantage.", ["Dedicated intelligence pod", "Custom evidence systems", "Board and investment committee support", "Long-horizon research"]]].map(([title, tagline, text, features], i) => <div className={`price-card ${i === 1 ? "featured" : ""}`} key={title as string}>{i === 1 && <span className="featured-label">Most selected</span>}<span className="mono-label">0{i + 1} / ACCESS</span><h2>{title as string}</h2><h3>{tagline as string}</h3><p>{text as string}</p><div>{(features as string[]).map(feature => <span key={feature}><Check size={14} />{feature}</span>)}</div><a className={`button ${i === 1 ? "primary" : "ghost"}`} href="/contact">Start a conversation <ArrowRight size={14} /></a></div>)}</section></main>; }

function Contact() { const { lang } = useLang(); const [sent, setSent] = useState(false); function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSent(true); track("contact_submit"); } return <main className="contact-page"><div className="contact-copy"><span className="kicker"><i>01</i>{tr(lang, "Start a Decision Sprint", "Iniciar un Decision Sprint")}</span><h1>{tr(lang, "Bring us a decision", "Tráenos una decisión")}<br /><em>{tr(lang, "that matters.", "que importe.")}</em></h1><p>{tr(lang, "Tell us what must be decided, the cost of being wrong and what evidence is missing. We’ll respond with the smallest useful next step.", "Cuéntanos qué debe decidirse, cuál es el costo de equivocarse y qué evidencia falta. Responderemos con el siguiente paso más útil.")}</p><div className="contact-proof"><CircleCheck size={15} /><span>{tr(lang, "Confidential by default", "Confidencial por defecto")}</span><CircleCheck size={15} /><span>{tr(lang, "No generic demos", "Sin demos genéricas")}</span></div></div><form onSubmit={submit}><span className="mono-label">{tr(lang, "DECISION INTAKE", "INGRESO DE DECISIÓN")}</span><label>{tr(lang, "Name", "Nombre")}<input required name="name" placeholder={tr(lang, "Your name", "Tu nombre")} /></label><label>{tr(lang, "Work email", "Correo de trabajo")}<input required type="email" name="email" placeholder="you@company.com" /></label><label>{tr(lang, "Company", "Compañía")}<input required name="company" placeholder={tr(lang, "Organization", "Organización")} /></label><label>{tr(lang, "Decision / Project", "Decisión / Proyecto")}<textarea required name="decision" rows={5} placeholder={tr(lang, "The decision, the deadline and what is at stake…", "La decisión, el plazo y lo que está en juego…")} /></label><button className="button primary" type="submit">{sent ? tr(lang, "Request received", "Solicitud recibida") : tr(lang, "Start the conversation", "Iniciar la conversación")} <Send size={15} /></button>{sent && <p className="form-note">{tr(lang, "Thank you. We’ll follow up with a focused next step.", "Gracias. Te contactaremos con un siguiente paso concreto.")}</p>}<small>{tr(lang, "Do not include confidential, regulated or sensitive personal information.", "No incluyas información confidencial, regulada o sensible.")}</small></form></main>; }

function HowItWorks() { const { lang } = useLang(); return <main className="interior-page"><section className="interior-hero"><span className="kicker"><i>01</i>{tr(lang, "How Sagar works", "Cómo funciona Sagar")}</span><h1>{tr(lang, "From uncertainty", "De la incertidumbre")}<br /><em>{tr(lang, "to a decision you can defend.", "a una decisión que puedes defender.")}</em></h1><p>{tr(lang, "A disciplined method for high-consequence decisions. Every step makes reality more legible.", "Un método disciplinado para decisiones críticas. Cada paso vuelve la realidad más legible.")}</p><a className="button primary" href="/contact">{tr(lang, "Start a Decision", "Iniciar una decisión")} <ArrowRight size={16} /></a></section><section className="method-journey">{process.map(([num, , text], i) => <div key={num}><span>{num}</span><div className="journey-marker"><div /></div><h2>{lang === "es" ? ["Entender", "Verificar", "Desafiar", "Comparar", "Transformar", "Decidir"][i] : ["Understand", "Verify", "Challenge", "Compare", "Transform", "Decide"][i]}</h2><p>{lang === "es" ? ["Enmarcamos el objetivo y el costo de equivocarse.", "Separamos hechos, fuentes y señales débiles.", "Hacemos visibles los supuestos y las contradicciones.", "Ponemos los caminos estratégicos lado a lado.", "Buscamos oportunidades más allá de la pregunta original.", "Recomendamos el camino mejor respaldado."][i] : text}</p></div>)}</section><section className="interior-split"><SectionIntro index="02" eyebrow={tr(lang, "The output", "El resultado")} title={<>{tr(lang, "Not more information.", "No más información.")}<br /><em>{tr(lang, "A better next move.", "Un mejor próximo paso.")}</em></>} text={tr(lang, "The final layer is designed for executive use: recommendation, why, risks, opportunities, actions and what could change the decision.", "La capa final está diseñada para uso ejecutivo: recomendación, razones, riesgos, oportunidades, acciones y qué podría cambiar la decisión.")} /><a className="button ghost" href="/ceo-summary">{tr(lang, "See the CEO Summary", "Ver el resumen para CEO")} <ArrowRight size={15} /></a></section></main>; }

function DecisionIntelligencePage() { const { lang } = useLang(); return <main className="interior-page"><section className="interior-hero"><span className="kicker"><i>01</i>{tr(lang, "Decision Intelligence", "Inteligencia de decisiones")}</span><h1>{tr(lang, "Connect the reality", "Conecta la realidad")}<br /><em>{tr(lang, "before it shapes the outcome.", "antes de que defina el resultado.")}</em></h1><p>{tr(lang, "Sagar connects evidence, risk, opportunity and scenario paths into one auditable decision view.", "Sagar conecta evidencia, riesgo, oportunidad y caminos de escenario en una sola vista de decisión auditable.")}</p></section><section className="intelligence-layers">{[[Globe2, "Reality", "What is happening around the project."], [FileSearch, "Evidence", "What supports or weakens the view."], [CircleAlert, "Risk", "What could make the decision fail."], [Sparkles, "Opportunity", "What becomes possible when the frame changes."], [BarChart3, "Scenario", "What each path requires and returns."], [Target, "Decision", "What to do next, and why."]].map(([Icon, title, text], i) => { const LayerIcon = Icon as IconType; return <div key={title as string}><span>0{i + 1}</span><LayerIcon size={18} /><h3>{lang === "es" ? ["Realidad", "Evidencia", "Riesgo", "Oportunidad", "Escenario", "Decisión"][i] : title as string}</h3><p>{lang === "es" ? ["Qué ocurre alrededor del proyecto.", "Qué respalda o debilita la lectura.", "Qué podría hacer fallar la decisión.", "Qué se vuelve posible al cambiar el marco.", "Qué exige y qué devuelve cada camino.", "Qué hacer después, y por qué."][i] : text as string}</p></div>; })}</section><section className="interior-split alt"><SectionIntro index="02" eyebrow={tr(lang, "Governed by design", "Gobernado por diseño")} title={<>{tr(lang, "Unknowns remain", "Las incógnitas permanecen")}<br /><em>{tr(lang, "visible until resolved.", "visibles hasta resolverse.")}</em></>} text={tr(lang, "Sagar does not turn missing evidence into false certainty. High-stakes recommendations may require expert review.", "Sagar no convierte la evidencia faltante en falsa certeza. Las recomendaciones críticas pueden requerir revisión experta.")} /><a className="text-link" href="/evidence-explorer">{tr(lang, "Explore the evidence trail", "Explorar la trazabilidad de evidencia")} <ArrowRight size={15} /></a></section></main>; }

function UseCases() { const { lang } = useLang(); const cases = lang === "es" ? [["Desarrollo de infraestructura", "Entender las dependencias que determinan si un proyecto puede ejecutarse."], ["Centros de datos e IA", "Conectar energía, agua, sitio, demanda y entrega."], ["Energía", "Evaluar restricciones de red, generación e interconexión."], ["Proyectos industriales", "Reducir sorpresas antes de comprometer capital y calendario."], ["Selección de sitios", "Comparar lugares con evidencia operativa y estratégica."], ["Pre-diligencia de inversión", "Ver qué está probado, qué falta y qué puede cambiar el caso."], ["Gobierno y desarrollo económico", "Convertir señales regionales en decisiones de infraestructura."], ["Manufactura", "Hacer visibles las dependencias de suministro y ejecución."]] : [["Infrastructure Development", "Understand the dependencies that determine whether a project can execute."], ["Data Centers & AI Infrastructure", "Connect power, water, site, demand and delivery."], ["Energy", "Evaluate grid, generation and interconnection constraints."], ["Industrial Projects", "Reduce surprises before capital and schedule are committed."], ["Site Selection", "Compare locations with operational and strategic evidence."], ["Investment Pre-Diligence", "See what is proven, missing and decision-changing."], ["Government / Economic Development", "Turn regional signals into infrastructure decisions."], ["Manufacturing", "Make supply and execution dependencies visible."]]; return <main className="interior-page"><section className="interior-hero"><span className="kicker"><i>01</i>{tr(lang, "Use cases", "Casos de uso")}</span><h1>{tr(lang, "Where the decision", "Donde la decisión")}<br /><em>{tr(lang, "carries weight.", "tiene consecuencias.")}</em></h1><p>{tr(lang, "Sagar is built for teams making complex choices across physical systems, capital and public consequence.", "Sagar está diseñado para equipos que toman decisiones complejas en sistemas físicos, capital y asuntos de interés público.")}</p></section><section className="use-case-grid">{cases.map(([title, text], i) => <a href="/contact" key={title}><span>0{i + 1}</span><h2>{title}</h2><p>{text}</p><ArrowRight size={16} /></a>)}</section><section className="interior-split"><SectionIntro index="02" eyebrow={tr(lang, "The common thread", "El hilo común")} title={<>{tr(lang, "Different domains.", "Dominios distintos.")}<br /><em>{tr(lang, "The same decision discipline.", "La misma disciplina de decisión.")}</em></>} text={tr(lang, "The question is always the same: what decision is being made, what is the cost of being wrong and what evidence is missing?", "La pregunta siempre es la misma: ¿qué decisión se está tomando, cuál es el costo de equivocarse y qué evidencia falta?")} /><a className="button primary" href="/contact">{tr(lang, "Bring us the decision", "Tráenos la decisión")} <ArrowRight size={15} /></a></section></main>; }

function ClientLogin() { const { lang } = useLang(); return <main className="login-page"><div className="login-card"><BrandMark /><span className="kicker"><i>01</i>{tr(lang, "Client access", "Acceso de clientes")}</span><h1>{tr(lang, "Your decision room is waiting.", "Tu sala de decisiones te espera.")}</h1><p>{tr(lang, "Client workspaces are private and invitation-only. Use the link from your Sagar Labs team.", "Los espacios de clientes son privados y solo funcionan por invitación. Usa el enlace de tu equipo de Sagar Labs.")}</p><button className="button primary" onClick={() => window.location.href = "/contact"}>{tr(lang, "Request access", "Solicitar acceso")} <ArrowRight size={15} /></button><small>{tr(lang, "Client Login placeholder · No credentials are collected on this page.", "Marcador de acceso · Esta página no recopila credenciales.")}</small></div></main>; }

export function Experience({ initialPath = "/" }: { initialPath?: string }) {
  const [theme, setTheme] = useState<"dark" | "light">("dark");
  const [lang, setLangState] = useState<Lang>("en");

  useEffect(() => {
    const saved = window.localStorage.getItem("sagar-language");
    // Restore the user's explicit preference after the client hydrates.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    if (saved === "en" || saved === "es") setLangState(saved);
  }, []);

  useEffect(() => {
    document.documentElement.lang = lang;
  }, [lang]);

  function setLang(value: Lang) {
    setLangState(value);
    window.localStorage.setItem("sagar-language", value);
  }

  const path = initialPath.replace(/\/$/, "") || "/";
  let page: React.ReactNode = <Home />;
  if (path === "/how-it-works") page = <HowItWorks />;
  else if (path === "/infrastructure-signal") page = <InfrastructureSignalPage lang={lang} />;
  else if (path === "/decision-intelligence") page = <DecisionIntelligencePage />;
  else if (path === "/decision-room") page = <DecisionRoomPage />;
  else if (path === "/scenario-explorer") page = <ScenarioExplorer />;
  else if (path === "/evidence-explorer") page = <EvidenceExplorer />;
  else if (path === "/ceo-summary") page = <CEOPage />;
  else if (path === "/use-cases") page = <UseCases />;
  else if (path === "/client-login") page = <ClientLogin />;
  else if (path === "/about") page = <About />;
  else if (path === "/pricing") page = <Pricing />;
  else if (path === "/contact") page = <Contact />;

  return <div className={`experience-shell theme-${theme}`}><LanguageContext.Provider value={{ lang, setLang }}><Header theme={theme} setTheme={setTheme} />{page}<Footer /></LanguageContext.Provider></div>;
}
